### ISSUE TITLE
Have the audio on loop

### ISSUE THREAD

**Issue by Kevin-RB** [camiladoss/JS-practice#1]
@camiladoss Consider having the Pókemon song on a loop by adding the **loop** attribute :smile:.

## Current code:
https://github.com/camiladoss/JS-practice/blob/30bda79c880494f0636d8bb9d9b363b7a1d8033e/Test11-FrontEnd/index.html#L33-L35

## Suggested changes:
```
    <audio autoplay loop id="myaudio">
        <source src="audio/Pokemon Song.mp3">
    </audio>
````

More information on this at [MDN Audio](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio#attr-loop).

**Comment by camiladoss** [comment]
Changes were done, thanks
